Support remote mode sources + misc
You can choose if you want to sync from gitea or github with the -r
option argument
Also handle mkdir error edge case and use flags + functions for main.

diff --git a/vimsync b/vimsync
--- a/vimsync
+++ b/vimsync
@@ -1,89 +1,116 @@
 #!/bin/sh
 
-#################
-### Variables ###
-#################
-
 XDG_CONFIG_HOME="$HOME/.config"
 XDG_DATA_HOME="$HOME/.local/share"
 
-# I need to implement an argument for the remote option to specify
-# the git remote to be used (use getopts)
-
-vimrc_url="https://git.leonardgomez.xyz/leg7/dotfiles/raw/branch/x200/home/user/.config/vim/vimrc"
-kwinrc_url="https://git.leonardgomez.xyz/leg7/vimsync/raw/branch/master/kwinrc"
-kshortcuts_url="https://git.leonardgomez.xyz/leg7/vimsync/raw/branch/master/kglobalshortcutsrc"
-konsole_url="https://git.leonardgomez.xyz/leg7/vimsync/raw/branch/master/nord.colorscheme"
-urls="$vimrc_url $kwinrc_url $kshortcuts_url $konsole_url"
-
-#################
-### Functions ###
-#################
-
-cp_error ()
+cp_error()
 {
 	echo "Error copying config files, aborting"
 	exit 1
 }
 
-wget_error ()
+wget_error()
 {
 	echo "Error fetching config files, aborting"
 	exit 1
 }
 
-mv_error ()
+mv_error()
 {
 	echo "Error moving config files, aborting"
 	echo "Files that couldn't be moved will be left in this directory"
 	exit 1
 }
 
-print_help ()
+print_help()
 {
 	printf "USAGE:
 	\t./vimsync OPTION
 	OPTIONS:
-	\tlocal,  l: sync with local files (you need to have cloned the repo for this to work)
-	\tremote, r: sync the configuration remotely (you only need the script for this to work)\n"
+	\t-h       : show this help message
+	\t-l       : sync with local files (you need to have cloned the repo for this to work)
+	\t-r REMOTE: sync remotely from remote, possible values for REMOTE are 'github' or 'gitea'\n"
 }
 
-syntax_error ()
+syntax_error()
 {
 	print_help
 	exit 1
 }
 
-##############
-### Import ###
-##############
+mkdir_error()
+{
+  echo "Error creating directory, aborting"
+  exit 1
+}
 
-mkdir -p "$XDG_CONFIG_HOME"/vim
+local_sync()
+{
+	cp -i ./vimrc          "$XDG_CONFIG_HOME"/vim/vimrc &&
+	cp -i kwirc            "$XDG_CONFIG_HOME"/kwinrc &&
+	cp -i kglobalshortcuts "$XDG_CONFIG_HOME"/kglobalshortcutsrc &&
+	cp -i nord.colorscheme "$XDG_DATA_HOME"/konsole/nord.colorscheme ||
+	cp_error
+}
 
-case $1 in
-	(local | l)
-		cp -i ./vimrc          "$XDG_CONFIG_HOME"/vim/vimrc &&
-		cp -i kwirc            "$XDG_CONFIG_HOME"/kwinrc &&
-		cp -i kglobalshortcuts "$XDG_CONFIG_HOME"/kglobalshortcutsrc &&
-		cp -i nord.colorscheme "$XDG_DATA_HOME"/konsole/nord.colorscheme ||
-		cp_error
-		;;
-	(remote | r)
-		for url in $urls
-		do
-			wget -q "$url" || wget_error
-		done
+remote_sync()
+{
+	for url in $url_list; do
+		wget -q "$url" || wget_error
+	done
 
-		mv -i ./vimrc          "$XDG_CONFIG_HOME"/vim/vimrc &&
-		mv -i kwirc            "$XDG_CONFIG_HOME"/kwinrc &&
-		mv -i kglobalshortcuts "$XDG_CONFIG_HOME"/kglobalshortcutsrc &&
-		mv -i nord.colorscheme "$XDG_DATA_HOME"/konsole/nord.colorscheme ||
-		mv_error
-		;;
-	(*)
-		syntax_error
-		;;
-esac
+	mv -i ./vimrc          "$XDG_CONFIG_HOME"/vim/vimrc &&
+	mv -i kwirc            "$XDG_CONFIG_HOME"/kwinrc &&
+	mv -i kglobalshortcuts "$XDG_CONFIG_HOME"/kglobalshortcutsrc &&
+	mv -i nord.colorscheme "$XDG_DATA_HOME"/konsole/nord.colorscheme ||
+	mv_error
+}
+
+local_mode=false
+remote_mode=false
+
+while getopts lr:h option; do
+	case $option in
+		(l)
+			local_mode=true;;
+		(r)
+			remote_mode=true
+			remote="$OPTARG"
+
+			if [ "$remote" = "github" ]
+			then
+				base="https://raw.githubusercontent.com"
+				vimrc_url="$base/leg7/dotfiles/x200/home/user/.config/vim/vimrc"
+				kwinrc_url="$base/leg7/vimsync/master/kwinrc"
+				kshortcuts_url="$base/leg7/vimsync/master/kglobalshortcutsrc"
+				konsole_url="$base/leg7/vimsync/master/nord.colorscheme"
+			elif [ "$remote" = "gitea" ]
+			then
+				base="https://git.leonardgomez.xyz"
+				vimrc_url="$base/leg7/dotfiles/raw/branch/x200/home/user/.config/vim/vimrc"
+				kwinrc_url="$base/leg7/vimsync/raw/branch/master/kwinrc"
+				kshortcuts_url="$base/leg7/vimsync/raw/branch/master/kglobalshortcutsrc"
+				konsole_url="$base/leg7/vimsync/raw/branch/master/nord.colorscheme"
+			else
+				syntax_error
+			fi
+			url_list="$vimrc_url $kwinrc_url $kshortcuts_url $konsole_url";;
+		(h | *)
+			syntax_error;;
+	esac
+done
+
+mkdir -p "$XDG_CONFIG_HOME"/vim || mkdir_error
+
+if $local_mode && $remote_mode; then
+	syntax_error
+elif $local_mode; then
+	local_sync
+elif $remote_mode; then
+	remote_sync
+else
+	syntax_error
+fi
 
 #################
 ### Configure ###
