Use functions to handle error messages

diff --git a/vimsync b/vimsync
--- a/vimsync
+++ b/vimsync
@@ -16,11 +16,43 @@ kshortcuts_url="https://git.leonardgomez.xyz/leg7/vimsync/raw/branch/master/kglo
 konsole_url="https://git.leonardgomez.xyz/leg7/vimsync/raw/branch/master/nord.colorscheme"
 urls="$vimrc_url $kwinrc_url $kshortcuts_url $konsole_url"
 
-help_msg="USAGE:
-\t./vimsync OPTION
-OPTIONS:
-\tlocal,  l: sync with local files (you need to have cloned the repo for this to work)
-\tremote, r: sync the configuration remotely (you only need the script for this to work)"
+#################
+### Functions ###
+#################
+
+cp_error ()
+{
+	echo "Error copying config files, aborting"
+	exit 1
+}
+
+wget_error ()
+{
+	echo "Error fetching config files, aborting"
+	exit 1
+}
+
+mv_error ()
+{
+	echo "Error moving config files, aborting"
+	echo "Files that couldn't be moved will be left in this directory"
+	exit 1
+}
+
+print_help ()
+{
+	printf "USAGE:
+	\t./vimsync OPTION
+	OPTIONS:
+	\tlocal,  l: sync with local files (you need to have cloned the repo for this to work)
+	\tremote, r: sync the configuration remotely (you only need the script for this to work)\n"
+}
+
+syntax_error ()
+{
+	print_help
+	exit 1
+}
 
 ##############
 ### Import ###
@@ -34,40 +66,28 @@ case $1 in
 		cp -i kwirc            "$XDG_CONFIG_HOME"/kwinrc &&
 		cp -i kglobalshortcuts "$XDG_CONFIG_HOME"/kglobalshortcutsrc &&
 		cp -i nord.colorscheme "$XDG_DATA_HOME"/konsole/nord.colorscheme ||
-		{
-			echo "Error copying config files, aborting"
-			exit 1
-		}
+		cp_error
 		;;
 	(remote|r)
 		for url in $urls
 		do
-			wget -q "$url" ||
-			{
-				echo "Error fetching config files, aborting"
-				exit 1
-			}
+			wget -q "$url" || wget_error
 		done
 
 		mv -i ./vimrc          "$XDG_CONFIG_HOME"/vim/vimrc &&
 		mv -i kwirc            "$XDG_CONFIG_HOME"/kwinrc &&
 		mv -i kglobalshortcuts "$XDG_CONFIG_HOME"/kglobalshortcutsrc &&
 		mv -i nord.colorscheme "$XDG_DATA_HOME"/konsole/nord.colorscheme ||
-		{
-			echo "Error moving config files, aborting"
-			echo "Files that couldn't be moved will be left in this directory"
-			exit 1
-		}
+		mv_error
 		;;
 	(*)
-		echo "$help_msg"
-		exit 1
+		syntax_error
 		;;
 esac
 
-###############
-## Configure ##
-###############
+#################
+### Configure ###
+#################
 
 # I should make the bashrc source a shell script with my config instead
 
